"""
Sustainability Analyzer — domain-specific reasoning for ESG metrics
using AlloyDB data + Gemini Flash.
"""

from __future__ import annotations

from typing import Any

from src.reasoning_engine.gemini_client import GeminiClient


class SustainabilityAnalyzer:
    """
    Domain-specific reasoning layer for ESG (Environmental, Social, Governance)
    metrics stored in AlloyDB.

    All analysis is delegated to Gemini with a sustainability-expert system
    prompt. Two entry points are provided:
      - ``analyze_carbon_footprint`` — per-department operational data.
      - ``generate_esg_report_section`` — aggregated KPIs for annual reporting.
    """

    # Shared system prompt applied to every Gemini call from this class.
    SYSTEM_PROMPT = (
        "You are an ESG and sustainability expert. Analyze environmental "
        "and operational data. Provide actionable recommendations for "
        "reducing carbon footprint and improving resource efficiency."
    )

    def __init__(self) -> None:
        """Initialise with a default GeminiClient using environment config."""
        self.gemini = GeminiClient()

    def analyze_carbon_footprint(self, data: list[dict[str, Any]]) -> str:
        """
        Analyse per-department carbon, energy, and waste metrics.

        Formats the raw AlloyDB rows into a bullet-point context block, then
        asks Gemini to identify the highest-impact departments, set reduction
        targets, and estimate cost savings from efficiency measures.

        Parameters
        ----------
        data:
            List of row dicts from the ``sustainability_metrics`` table.
            Expected keys: ``department``, ``carbon_kg``, ``energy_kwh``,
            ``waste_kg``.

        Returns
        -------
        str
            Gemini's structured ESG analysis with actionable recommendations.
        """
        # Build a compact bullet list so Gemini gets clear, structured input.
        context = "\n".join(
            f"- {r.get('department','N/A')}: {r.get('carbon_kg',0)} kg CO2, "
            f"{r.get('energy_kwh',0)} kWh, {r.get('waste_kg',0)} kg waste"
            for r in data
        )
        prompt = f"""## Carbon Footprint Data
{context}

Provide: 1) Highest impact departments 2) Reduction targets
3) Quick wins vs long-term strategies 4) Estimated cost savings"""

        # Low temperature — we want precise, data-driven recommendations.
        return self.gemini.generate(
            prompt=prompt, system_instruction=self.SYSTEM_PROMPT, temperature=0.2
        )

    def generate_esg_report_section(self, metrics: dict[str, Any]) -> str:
        """
        Draft a 2-3 paragraph ESG report section from aggregated KPIs.

        Suitable for inclusion in annual sustainability disclosures (GRI, TCFD,
        or CDP frameworks). Slightly higher temperature allows for more polished,
        report-ready prose while keeping figures accurate.

        Parameters
        ----------
        metrics:
            Dictionary of aggregated sustainability KPIs. Expected keys:
            ``total_emissions_tons``, ``yoy_change_pct``, ``renewable_pct``,
            ``water_cubic_m``, ``waste_diversion_pct``.

        Returns
        -------
        str
            Report-ready paragraph text generated by Gemini.
        """
        prompt = f"""Generate ESG report section:
- Emissions: {metrics.get('total_emissions_tons','N/A')} tons CO2e
- YoY change: {metrics.get('yoy_change_pct','N/A')}%
- Renewable share: {metrics.get('renewable_pct','N/A')}%
- Water: {metrics.get('water_cubic_m','N/A')} m³
- Waste diversion: {metrics.get('waste_diversion_pct','N/A')}%

Write 2-3 paragraphs for an annual sustainability report."""

        # Slightly higher temperature for fluent, professional prose.
        return self.gemini.generate(
            prompt=prompt, system_instruction=self.SYSTEM_PROMPT, temperature=0.4
        )
