"""
Vector search — cosine similarity against AlloyDB embeddings.
Queries are embedded on-the-fly and matched against pre-computed vectors.
"""

from typing import Optional
import sqlalchemy
import structlog
from sqlalchemy import text
from src.config import get_engine
from src.security.secure_connection import SecureConnection

logger = structlog.get_logger(__name__)


class VectorSearch:
    """
    Semantic similarity search over AlloyDB vector embeddings.

    Embeddings are pre-generated by ``infra/seed_data.sql`` using
    ``google_ml.embedding()`` in batch (no per-row Python loops). Search
    queries are embedded inline at query time — also inside AlloyDB — so no
    extra Vertex AI call is needed from Python.

    The ``<=>`` operator is AlloyDB's cosine distance operator for pgvector.
    Similarity score = ``1 - cosine_distance`` (range 0–1, higher is closer).
    """

    def __init__(self, engine: sqlalchemy.engine.Engine = None):
        """
        Parameters
        ----------
        engine:
            SQLAlchemy engine connected to AlloyDB. Created from environment
            config if not provided.
        """
        self.engine = engine or get_engine()

    def search_employees(self, query: str, top_k: int = 10,
                         active_user: Optional[str] = None) -> list[dict]:
        """
        Find the *top_k* employees whose profile embedding is closest to *query*.

        The query text is embedded inside AlloyDB via ``google_ml.embedding()``,
        avoiding a separate Python-to-Vertex round-trip. Results are filtered
        by RLS so the caller only sees employees they are authorised to view.

        Parameters
        ----------
        query:
            Free-text search string (e.g. ``"senior engineer cloud infrastructure"``).
        top_k:
            Maximum number of results to return.
        active_user:
            RLS context username. Employees see only their own record;
            managers see their department; admins see all.

        Returns
        -------
        list[dict]
            Each dict contains ``id``, ``name``, ``department``, ``role``,
            ``salary``, and ``similarity`` score.
        """
        sql = text("""
            SELECT e.id, e.name, e.department, e.role, e.salary,
                   1 - (e.embedding <=> google_ml.embedding(
                       model_id => 'text-embedding-005', content => :query
                   )::vector) AS similarity
            FROM employees e
            WHERE e.embedding IS NOT NULL
            ORDER BY e.embedding <=> google_ml.embedding(
                model_id => 'text-embedding-005', content => :query
            )::vector
            LIMIT :top_k;
        """)
        with SecureConnection(self.engine, active_user) as conn:
            result = conn.execute(sql, {"query": query, "top_k": top_k})
            cols = list(result.keys())
            rows = [dict(zip(cols, r)) for r in result.fetchall()]
        logger.info("Vector search complete", query_preview=query[:40], result_count=len(rows))
        return rows

    def search_reviews(self, query: str, top_k: int = 10,
                       active_user: Optional[str] = None) -> list[dict]:
        """
        Find the *top_k* performance reviews semantically closest to *query*.

        Joins back to ``employees`` so the result includes the employee name
        alongside the review content. RLS on both tables is enforced via the
        active user context.

        Parameters
        ----------
        query:
            Free-text search string (e.g. ``"exceeded targets leadership"``).
        top_k:
            Maximum number of results to return.
        active_user:
            RLS context username.

        Returns
        -------
        list[dict]
            Each dict contains ``id``, ``name``, ``rating``, ``review_text``,
            ``review_date``, and ``similarity`` score.
        """
        sql = text("""
            SELECT pr.id, e.name, pr.rating, pr.review_text, pr.review_date,
                   1 - (pr.embedding <=> google_ml.embedding(
                       model_id => 'text-embedding-005', content => :query
                   )::vector) AS similarity
            FROM performance_reviews pr
            JOIN employees e ON e.id = pr.employee_id
            WHERE pr.embedding IS NOT NULL
            ORDER BY pr.embedding <=> google_ml.embedding(
                model_id => 'text-embedding-005', content => :query
            )::vector
            LIMIT :top_k;
        """)
        with SecureConnection(self.engine, active_user) as conn:
            result = conn.execute(sql, {"query": query, "top_k": top_k})
            cols = list(result.keys())
            return [dict(zip(cols, r)) for r in result.fetchall()]

    def get_embedding_stats(self) -> list[dict]:
        """
        Return coverage statistics showing how many rows have embeddings.

        Useful for monitoring batch embedding progress after running
        ``infra/seed_data.sql`` or the ``VectorEngine.embed_pending()`` job.

        Returns
        -------
        list[dict]
            Two rows — one per table — each with ``tbl``, ``total``,
            and ``embedded`` counts.
        """
        sql = text("""
            SELECT 'employees' AS tbl, COUNT(*) AS total,
                   COUNT(embedding) AS embedded
            FROM employees
            UNION ALL
            SELECT 'performance_reviews', COUNT(*), COUNT(embedding)
            FROM performance_reviews;
        """)
        with self.engine.connect() as conn:
            result = conn.execute(sql)
            return [dict(zip(result.keys(), r)) for r in result.fetchall()]
